syntax = "proto3";

package Icy.Asset;


message AssetSetting
{
	//YooAsset的默认Package的名字，比如 "DefaultPackage"
	string DefaultPackageName = 1;
    //热更新资源Host地址（主）
    string AssetHostServerAddressMain = 2;
    //热更新资源Host地址（备）
    string AssetHostServerAddressStandby = 3;
	//打包过程中，会将HybridCLR编译出的热更DLL，Copy到此目录，方便业务侧将其打包成AB
    string PatchDLLCopyToDir = 4;
	//在BuildWindow执行HybridCLR Generate All时，会将生成的补充元数据DLL，Copy到此目录，方便业务侧将其打包成AB
	string MetaDataDLLCopyToDir = 5;
	//在非WIFI、非网线的网络环境下，下载资源量大于此值时，通知业务侧是否要开始下载，否则直接开始下载，单位MB
	int32 AssetDownloadConfirmTheshold = 6;

	//HybridCLR热更DLL列表
	repeated string PatchDLLs = 14;
	//HybridCLR补充元数据DLL列表
	repeated string MetaDataDLLs = 15;
}
